# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOFaNph-1D4uLaP9kqhEFoFwY5haGbuw
"""

import streamlit as st
import numpy as np
import joblib

# Load the trained model
model = joblib.load('xgboost_model.pkl')

# Title
st.title("🔥 Calorie Burn Prediction App")

st.markdown("""
This app uses an XGBoost model to predict how many calories you'll burn during a workout based on your personal metrics.
""")

# Input form
sex = st.selectbox("Sex", ["Male", "Female"])
age = st.slider("Age", 10, 100, 25)
height = st.number_input("Height (cm)", min_value=100.0, max_value=250.0, value=170.0)
weight = st.number_input("Weight (kg)", min_value=30.0, max_value=200.0, value=70.0)
duration = st.number_input("Duration of Workout (minutes)", min_value=1.0, max_value=300.0, value=30.0)
heart_rate = st.number_input("Heart Rate (bpm)", min_value=40.0, max_value=220.0, value=120.0)
body_temp = st.number_input("Body Temperature (°C)", min_value=35.0, max_value=42.0, value=37.0)

# Encode 'Sex' manually (assuming model was trained with Male=1, Female=0)
sex_encoded = 1 if sex == "Male" else 0

# Predict button
if st.button("Predict Calories Burned"):
    features = np.array([[sex_encoded, age, height, weight, duration, heart_rate, body_temp]])
    prediction = model.predict(features)[0]
    st.success(f"🔥 Estimated Calories Burned: **{prediction:.2f} kcal**")